import { StartupIdea, GrowthPhase, GrowthStory, DashboardMetrics } from "./types";

export const sampleIdeas: StartupIdea[] = [
  {
    id: "1",
    title: "AI Resume Optimizer",
    hook: "Beat the ATS bots and land 3x more interviews",
    problem: "90% of resumes get rejected by Applicant Tracking Systems before a human ever sees them",
    solution: "AI-powered resume analysis and optimization tool that scores resumes against job descriptions and suggests targeted improvements",
    revenueModel: "Freemium SaaS - $19/mo Pro, $49/mo Enterprise",
    costRange: "$500 - $2,000",
    riskLevel: "Low",
    scalabilityScore: 85,
    trendScore: 92,
    whyNow: "Remote work explosion has made job applications 5x more competitive",
    aiMatchPercent: 94,
    category: "SaaS",
    industry: "HR Tech",
    region: "Global",
  },
  {
    id: "2",
    title: "Micro-SaaS Invoice Automation",
    hook: "Freelancers lose 5hrs/week on invoicing. Fix that.",
    problem: "Freelancers and solopreneurs waste hours creating, sending, and tracking invoices manually",
    solution: "Auto-generate branded invoices from project management tools, send payment reminders, and reconcile payments",
    revenueModel: "Subscription - $12/mo Starter, $29/mo Growth",
    costRange: "$1,000 - $3,000",
    riskLevel: "Low",
    scalabilityScore: 78,
    trendScore: 75,
    whyNow: "Freelance economy growing 3x faster than traditional employment",
    aiMatchPercent: 88,
    category: "Micro-SaaS",
    industry: "FinTech",
    region: "Global",
  },
  {
    id: "3",
    title: "AI-Powered Local Service Marketplace",
    hook: "Uber for home services, powered by AI matching",
    problem: "Finding reliable local service providers is a frustrating experience with no quality guarantees",
    solution: "AI-matched marketplace connecting homeowners with vetted local pros, with dynamic pricing and quality scoring",
    revenueModel: "Commission 15-20% per transaction",
    costRange: "$5,000 - $15,000",
    riskLevel: "High",
    scalabilityScore: 92,
    trendScore: 80,
    whyNow: "Home services market reaching $600B with poor digital penetration",
    aiMatchPercent: 76,
    category: "Marketplace",
    industry: "Home Services",
    region: "Regional",
  },
  {
    id: "4",
    title: "Creator Analytics Dashboard",
    hook: "One dashboard for all your creator metrics",
    problem: "Content creators juggle 5+ platforms with no unified view of their performance and revenue",
    solution: "Unified analytics dashboard pulling data from YouTube, TikTok, Instagram, Twitter, and Patreon into one view",
    revenueModel: "SaaS - $15/mo Creator, $39/mo Agency",
    costRange: "$2,000 - $5,000",
    riskLevel: "Medium",
    scalabilityScore: 82,
    trendScore: 95,
    whyNow: "Creator economy is $100B+ and creators need professional-grade tools",
    aiMatchPercent: 91,
    category: "SaaS",
    industry: "Creator Economy",
    region: "Global",
  },
  {
    id: "5",
    title: "AI Study Buddy for Students",
    hook: "Your personal AI tutor that adapts to how you learn",
    problem: "Students struggle with self-study, lacking personalized guidance and motivation",
    solution: "AI tutor that creates custom study plans, generates practice questions, and adapts to learning patterns",
    revenueModel: "Freemium - $9.99/mo Student, $29.99/mo Family",
    costRange: "$1,500 - $4,000",
    riskLevel: "Medium",
    scalabilityScore: 90,
    trendScore: 88,
    whyNow: "EdTech market booming post-pandemic, AI making personalized learning possible",
    aiMatchPercent: 85,
    category: "EdTech",
    industry: "Education",
    region: "Global",
  },
  {
    id: "6",
    title: "Subscription Box Curation Platform",
    hook: "Launch a subscription box business in 48 hours",
    problem: "Entrepreneurs want to start subscription box businesses but sourcing, logistics, and tech are barriers",
    solution: "End-to-end platform to design, source, manage, and ship subscription boxes with built-in Shopify integration",
    revenueModel: "Platform fee $49/mo + 3% transaction fee",
    costRange: "$3,000 - $8,000",
    riskLevel: "Medium",
    scalabilityScore: 75,
    trendScore: 70,
    whyNow: "Subscription box market growing 20% YoY, reaching $65B by 2027",
    aiMatchPercent: 72,
    category: "E-commerce",
    industry: "Retail",
    region: "North America",
  },
  {
    id: "7",
    title: "Remote Team Culture Platform",
    hook: "Build team culture without an office",
    problem: "Remote teams suffer from isolation, poor communication, and weak culture leading to 2x higher turnover",
    solution: "Virtual watercooler with AI-powered team matching, async social activities, and culture health scoring",
    revenueModel: "Per-seat SaaS - $5/user/mo",
    costRange: "$3,000 - $10,000",
    riskLevel: "Medium",
    scalabilityScore: 88,
    trendScore: 85,
    whyNow: "70% of companies now hybrid/remote, culture tools are non-negotiable",
    aiMatchPercent: 79,
    category: "SaaS",
    industry: "HR Tech",
    region: "Global",
  },
  {
    id: "8",
    title: "Pet Health Tracker App",
    hook: "Fitbit for your furry friend",
    problem: "Pet owners miss early signs of health issues, leading to expensive vet bills and preventable conditions",
    solution: "AI health monitoring app that tracks pet behavior, diet, and activity patterns to flag health concerns early",
    revenueModel: "Freemium app + $7.99/mo Premium + Vet affiliate revenue",
    costRange: "$2,000 - $6,000",
    riskLevel: "Low",
    scalabilityScore: 80,
    trendScore: 78,
    whyNow: "Pet spending hit $136B, millennials treat pets like children",
    aiMatchPercent: 83,
    category: "Consumer App",
    industry: "Pet Care",
    region: "Global",
  },
  {
    id: "9",
    title: "No-Code Agency Toolkit",
    hook: "Run a digital agency without writing code",
    problem: "Small agencies struggle to deliver client projects profitably with traditional development approaches",
    solution: "Pre-built templates, client portal, project management, and white-label no-code tools for agency owners",
    revenueModel: "SaaS - $29/mo Solo, $79/mo Team, $199/mo Agency",
    costRange: "$4,000 - $12,000",
    riskLevel: "Medium",
    scalabilityScore: 85,
    trendScore: 90,
    whyNow: "No-code tools are mature enough, agency market is $500B+",
    aiMatchPercent: 87,
    category: "SaaS",
    industry: "Agency Tools",
    region: "Global",
  },
  {
    id: "10",
    title: "AI Meal Prep Planner",
    hook: "Eat healthy without thinking about it",
    problem: "People waste 3+ hours weekly planning meals and grocery shopping, often defaulting to unhealthy choices",
    solution: "AI generates personalized weekly meal plans based on dietary goals, budget, and local grocery deals",
    revenueModel: "Subscription $8.99/mo + Grocery delivery affiliate",
    costRange: "$1,000 - $3,000",
    riskLevel: "Low",
    scalabilityScore: 82,
    trendScore: 86,
    whyNow: "Health consciousness at all-time high, AI enables true personalization",
    aiMatchPercent: 90,
    category: "Consumer App",
    industry: "Health & Wellness",
    region: "Global",
  },
];

export const growthPhases: GrowthPhase[] = [
  {
    id: 1,
    title: "Idea Clarity",
    subtitle: "Define your problem, audience, and unique advantage",
    unlocked: true,
    lessons: [
      { id: "1-1", title: "Skill Audit", description: "Map your top 5 skills and identify your unfair advantage", xp: 50, completed: false, phase: 1, day: 1 },
      { id: "1-2", title: "Problem Discovery", description: "Interview 5 potential users and document their pain points", xp: 75, completed: false, phase: 1, day: 2 },
      { id: "1-3", title: "Market Validation", description: "Research market size and identify 3 direct competitors", xp: 100, completed: false, phase: 1, day: 3 },
      { id: "1-4", title: "Viability Scoring", description: "Score your idea across 10 criteria and calculate viability", xp: 75, completed: false, phase: 1, day: 4 },
      { id: "1-5", title: "Idea Statement", description: "Write your one-liner: For [audience] who [problem], [product] is a [category] that [benefit]", xp: 50, completed: false, phase: 1, day: 5 },
    ],
  },
  {
    id: 2,
    title: "Revenue Blueprint",
    subtitle: "Design your offer, pricing, and path to first customers",
    unlocked: false,
    lessons: [
      { id: "2-1", title: "Offer Design", description: "Define your core offer, features, and value proposition", xp: 75, completed: false, phase: 2, day: 6 },
      { id: "2-2", title: "Pricing Strategy", description: "Research competitor pricing and set your pricing tiers", xp: 100, completed: false, phase: 2, day: 7 },
      { id: "2-3", title: "MVP Definition", description: "Define minimum feature set for launch and create a wireframe", xp: 125, completed: false, phase: 2, day: 8 },
      { id: "2-4", title: "First 10 Customers", description: "Create outreach plan to acquire your first 10 paying customers", xp: 150, completed: false, phase: 2, day: 9 },
      { id: "2-5", title: "Revenue Model", description: "Build a simple spreadsheet projecting 6-month revenue", xp: 100, completed: false, phase: 2, day: 10 },
    ],
  },
  {
    id: 3,
    title: "Growth System",
    subtitle: "Build distribution, feedback loops, and automation",
    unlocked: false,
    lessons: [
      { id: "3-1", title: "Distribution Plan", description: "Identify top 3 channels to reach your audience and create content plan", xp: 100, completed: false, phase: 3, day: 11 },
      { id: "3-2", title: "Feedback Loop", description: "Set up user feedback system and conduct 5 user interviews", xp: 125, completed: false, phase: 3, day: 12 },
      { id: "3-3", title: "Automation Setup", description: "Automate onboarding emails, analytics tracking, and social posting", xp: 150, completed: false, phase: 3, day: 13 },
      { id: "3-4", title: "Scale Simulation", description: "Model what happens at 100, 1000, and 10000 users", xp: 125, completed: false, phase: 3, day: 14 },
      { id: "3-5", title: "Growth Review", description: "Analyze metrics, identify bottlenecks, and plan next sprint", xp: 100, completed: false, phase: 3, day: 15 },
    ],
  },
];

export const growthStories: GrowthStory[] = [
  {
    id: "1",
    founderName: "Sarah Chen",
    background: "Former marketing manager, no technical skills",
    initialCapital: "$500",
    revenueTimeline: "Hit $5K MRR in 4 months",
    pivotMoment: "Pivoted from B2C to B2B after realizing agencies would pay 10x more",
    keyLessons: ["Start with the audience you already have access to", "B2B is easier to monetize than B2C", "Ship fast, iterate faster"],
    tacticalInsights: ["Used LinkedIn DMs to get first 20 customers", "Free trial + onboarding call = 60% conversion", "Partnered with complementary tools for distribution"],
    category: "Bootstrapped",
    industry: "Marketing Tech",
    imageUrl: "",
    monthlyRevenue: "$12,000",
  },
  {
    id: "2",
    founderName: "Marcus Johnson",
    background: "College dropout, self-taught developer",
    initialCapital: "$0",
    revenueTimeline: "Hit $2K MRR in 2 months",
    pivotMoment: "Realized his side project solved a real pain point when strangers started asking to pay for it",
    keyLessons: ["Build what you use yourself", "Launch before you feel ready", "Revenue validates better than surveys"],
    tacticalInsights: ["Built in public on Twitter, gained 5K followers before launch", "Charged from day one", "Used Product Hunt for initial traction"],
    category: "Student Founder",
    industry: "Developer Tools",
    imageUrl: "",
    monthlyRevenue: "$8,500",
  },
  {
    id: "3",
    founderName: "Priya Patel",
    background: "Corporate consultant, MBA from top school",
    initialCapital: "$2,000",
    revenueTimeline: "Hit $10K MRR in 6 months",
    pivotMoment: "Narrowed from serving all businesses to only e-commerce brands",
    keyLessons: ["Niche down aggressively", "Your network is your unfair advantage", "Consulting revenue can fund product development"],
    tacticalInsights: ["Started as a service, productized over time", "Used case studies as top-of-funnel content", "Hired virtual assistants early to free up strategic time"],
    category: "Solo Founder",
    industry: "E-commerce",
    imageUrl: "",
    monthlyRevenue: "$25,000",
  },
  {
    id: "4",
    founderName: "Alex Rivera",
    background: "Software engineer at FAANG company",
    initialCapital: "$10,000",
    revenueTimeline: "Hit $50K MRR in 8 months after fundraise",
    pivotMoment: "Raised a $500K pre-seed after showing strong retention metrics",
    keyLessons: ["Retention matters more than acquisition", "Fundraising is a full-time job", "Hire for culture, train for skills"],
    tacticalInsights: ["Cold emailed 200 VCs, got 15 meetings, closed 2", "Used AngelList and Twitter for investor outreach", "Built a waitlist of 2K before launch"],
    category: "VC-backed",
    industry: "AI/ML",
    imageUrl: "",
    monthlyRevenue: "$85,000",
  },
];

export const defaultMetrics: DashboardMetrics = {
  validationStrength: 42,
  revenueReadiness: 28,
  marketFitIndex: 55,
  executionConsistency: 65,
  scalePotential: 38,
  dailyStreak: 7,
  xpPoints: 1250,
  badges: ["Early Adopter", "First Idea Saved", "Week One Streak", "Problem Hunter"],
};
